name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/build-dotnet.yml@main
    secrets: inherit
    with:
      project_path: 'Platform.Payment.sln'
      dependencies: 'Platform-System/Platform.Api,Platform-System/Platform.Application,Platform-System/Platform.Infrastructure,Platform-System/Platform.SystemContext,Platform-System/Platform.BuildingBlocks,Platform-System/Platform.SharedKernel,Platform-System/Platform.Domain,Platform-System/Platform.Contracts,Platform-System/Platform.Messaging'
      push_image: true
      image_name: 'platform-payment-api'
